name: Deploy Docker Compose on Push to Master

on:
  push:
    branches:
      - master  # Trigger only on master branch

jobs:
  docker-deploy:
    runs-on: ubuntu-latest  # Change to self-hosted if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Get the latest code

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Ensures Docker environment is ready

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and Run Docker Compose
        run: |
          docker-compose down  # Stop any running containers
          docker-compose pull  # Pull latest images (if using external images)
          docker-compose up -d  # Run containers in detached mode
